apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: efs-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: wordpress:latest
          volumeMounts:
            - name: myvolume
              mountPath: /var/www/html/wp-content/uploads
              subPath: uploads

      volumes:
        - name: myvolume
          persistentVolumeClaim:
              claimName: myvolume